// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjHZ-GrpXC8qyskcTG4XOIy_7l6qixuw',
    appId: '1:866054846232:web:f99849180f483d62c5d06d',
    messagingSenderId: '866054846232',
    projectId: 'doctor-dashboard-a77a1',
    authDomain: 'doctor-dashboard-a77a1.firebaseapp.com',
    storageBucket: 'doctor-dashboard-a77a1.firebasestorage.app',
    measurementId: 'G-6TVMGJN1YN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqmB7o7-RHK6jGVoAPXaGKhvuGdLEZ2tY',
    appId: '1:866054846232:android:7887aca890126ae7c5d06d',
    messagingSenderId: '866054846232',
    projectId: 'doctor-dashboard-a77a1',
    storageBucket: 'doctor-dashboard-a77a1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXQRtpv57PS3U7OpAbIb7tLr40zFpkexg',
    appId: '1:866054846232:ios:604ae7a8e8a087f1c5d06d',
    messagingSenderId: '866054846232',
    projectId: 'doctor-dashboard-a77a1',
    storageBucket: 'doctor-dashboard-a77a1.firebasestorage.app',
    iosBundleId: 'com.example.doctorDashboardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXQRtpv57PS3U7OpAbIb7tLr40zFpkexg',
    appId: '1:866054846232:ios:604ae7a8e8a087f1c5d06d',
    messagingSenderId: '866054846232',
    projectId: 'doctor-dashboard-a77a1',
    storageBucket: 'doctor-dashboard-a77a1.firebasestorage.app',
    iosBundleId: 'com.example.doctorDashboardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJjHZ-GrpXC8qyskcTG4XOIy_7l6qixuw',
    appId: '1:866054846232:web:58d3ca950ef566fcc5d06d',
    messagingSenderId: '866054846232',
    projectId: 'doctor-dashboard-a77a1',
    authDomain: 'doctor-dashboard-a77a1.firebaseapp.com',
    storageBucket: 'doctor-dashboard-a77a1.firebasestorage.app',
    measurementId: 'G-B55ZJ1TJLP',
  );
}
