import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire

// Screens
import 'screens/signup_screen.dart';
import 'screens/login_screen.dart';
import 'screens/dashboard_screen.dart';
import 'screens/patient_details_screen.dart';

// Models
import 'models/patient.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const DoctorDashboardApp());
}

class DoctorDashboardApp extends StatelessWidget {
  const DoctorDashboardApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Doctor Dashboard',
      debugShowCheckedModeBanner: false,
      theme: ThemeData.dark(),
      initialRoute: '/signup',
      routes: {
        '/': (context) => const SignupScreen(),
        '/signup': (context) => const SignupScreen(),
        '/login': (context) => const LoginScreen(),
        '/dashboard': (context) =>  DashboardScreen(),//const
        '/patientDetails': (context) {
          final patient =
              ModalRoute.of(context)!.settings.arguments as Patient;
          return PatientDetailsScreen(patient: patient);
        },
      },
    );
  }
}
